
name: Update Nexthour Gist

on:
  schedule:
    # Every 30 minutes
    - cron: "*/30 * * * *"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Fetch configs and update Gist
        env:
          NEXTHOUR_API_KEY: ${{ secrets.NEXTHOUR_API_KEY }}
          NEXTHOUR_CERT: ${{ secrets.NEXTHOUR_CERT }}
          NEXTHOUR_HMAC_KEY: ${{ secrets.NEXTHOUR_HMAC_KEY }}
          NEXTHOUR_PACKAGE: "com.gamenetvpn.pingbooster"

          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}

          SAVE_LOCAL: "false"

        run: |
          python nexthour_gist.py
